version: "3.1"
services:
  api:
    build: .
    volumes:
      - ./:/code/
    working_dir: /code
    environment:
      FLASK_APP: 'buscador-dni.py'
    command: 'flask run -p 3000 -h 0.0.0.0'
    ports:
      - "3000:3000"
